source 'https://github.com/CocoaPods/Specs.git'

target 'MUKUserNotificationController', :exclusive => true do
  pod "MUKUserNotificationController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MUKUserNotificationController", :path => "../"

  
end
